name: Deploy node Server
on:
    pull_request:
        branches:
            - udev
jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server/
        strategy:
            matrix:
                node-version: ["16.18.0"]
        env:
            MODE: ${{ secrets.MODE }}
        steps:
            - uses: actions/checkout@v4 # Pre made checkout to branch action
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}} # Run on each matrix version we provided
            - name: Install dependencies
              run: |
                  if [ -e yarn.lock ]; then
                  yarn install --frozen-lockfile
                  elif [ -e package-lock.json ]; then
                  npm ci
                  else
                  npm i
                  fi
            - name: Test server
              run: npm test
