name: Deploy node Server
on:
  pull_request:
    branches:
      - udev
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/
    strategy:
      matrix:
        node-version: ["16.18.0"]
    env:
      MODE: "dev"
    steps:
      - uses: actions/checkout@v4 # Pre made checkout to branch action
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}} # Run on each matricts version we provided
      - name: Install dependancies
        run: npm ci # Like npm install in automation
      - name: Test server
        run: npm test
